# Generated by Django 4.1.5 on 2023-02-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryID', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(max_length=250)),
                ('Product_Prices', models.CharField(max_length=250)),
                ('Product_CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
